name: local_database
description: A local database using dart:io file system components. Comes with put, get, and remove functionality.
version: 1.3.0
homepage: https://github.com/Blakexx/local_database

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  queue: ^3.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter