name: local_database_null_safety
description: A local null safety database based on local_database_null_safety https://github.com/Blakexx/local_database_null_safety
version: 1.4.1
homepage: https://github.com/spiderion/local_database_null_safe.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  queue: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter